/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as NewsEventsRouteImport } from './routes/news-events'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ManagementTeamRouteImport } from './routes/management-team'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChairmanMessageRouteImport } from './routes/chairman-message'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesStockBrokerageRouteImport } from './routes/services.stock-brokerage'
import { Route as ServicesResearchAdvisoryRouteImport } from './routes/services.research-advisory'
import { Route as ServicesPortfolioManagementRouteImport } from './routes/services.portfolio-management'
import { Route as ServicesMarginTradingRouteImport } from './routes/services.margin-trading'
import { Route as ServicesIpoFpoRouteImport } from './routes/services.ipo-fpo'
import { Route as ServicesDepositoryServicesRouteImport } from './routes/services.depository-services'
import { Route as MarketTopGainersLosersRouteImport } from './routes/market.top-gainers-losers'
import { Route as MarketSummaryRouteImport } from './routes/market.summary'
import { Route as MarketLiveRouteImport } from './routes/market.live'
import { Route as MarketFloorsheetRouteImport } from './routes/market.floorsheet'
import { Route as MarketChartRouteImport } from './routes/market.chart'
import { Route as BranchesSlugRouteImport } from './routes/branches.$slug'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEventsRoute = NewsEventsRouteImport.update({
  id: '/news-events',
  path: '/news-events',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementTeamRoute = ManagementTeamRouteImport.update({
  id: '/management-team',
  path: '/management-team',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanMessageRoute = ChairmanMessageRouteImport.update({
  id: '/chairman-message',
  path: '/chairman-message',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStockBrokerageRoute = ServicesStockBrokerageRouteImport.update({
  id: '/services/stock-brokerage',
  path: '/services/stock-brokerage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResearchAdvisoryRoute =
  ServicesResearchAdvisoryRouteImport.update({
    id: '/services/research-advisory',
    path: '/services/research-advisory',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPortfolioManagementRoute =
  ServicesPortfolioManagementRouteImport.update({
    id: '/services/portfolio-management',
    path: '/services/portfolio-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMarginTradingRoute = ServicesMarginTradingRouteImport.update({
  id: '/services/margin-trading',
  path: '/services/margin-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIpoFpoRoute = ServicesIpoFpoRouteImport.update({
  id: '/services/ipo-fpo',
  path: '/services/ipo-fpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDepositoryServicesRoute =
  ServicesDepositoryServicesRouteImport.update({
    id: '/services/depository-services',
    path: '/services/depository-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketTopGainersLosersRoute = MarketTopGainersLosersRouteImport.update({
  id: '/top-gainers-losers',
  path: '/top-gainers-losers',
  getParentRoute: () => MarketRoute,
} as any)
const MarketSummaryRoute = MarketSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => MarketRoute,
} as any)
const MarketLiveRoute = MarketLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => MarketRoute,
} as any)
const MarketFloorsheetRoute = MarketFloorsheetRouteImport.update({
  id: '/floorsheet',
  path: '/floorsheet',
  getParentRoute: () => MarketRoute,
} as any)
const MarketChartRoute = MarketChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => MarketRoute,
} as any)
const BranchesSlugRoute = BranchesSlugRouteImport.update({
  id: '/branches/$slug',
  path: '/branches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/management-team': typeof ManagementTeamRoute
  '/market': typeof MarketRouteWithChildren
  '/news-events': typeof NewsEventsRoute
  '/our-team': typeof OurTeamRoute
  '/support': typeof SupportRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/market/chart': typeof MarketChartRoute
  '/market/floorsheet': typeof MarketFloorsheetRoute
  '/market/live': typeof MarketLiveRoute
  '/market/summary': typeof MarketSummaryRoute
  '/market/top-gainers-losers': typeof MarketTopGainersLosersRoute
  '/services/depository-services': typeof ServicesDepositoryServicesRoute
  '/services/ipo-fpo': typeof ServicesIpoFpoRoute
  '/services/margin-trading': typeof ServicesMarginTradingRoute
  '/services/portfolio-management': typeof ServicesPortfolioManagementRoute
  '/services/research-advisory': typeof ServicesResearchAdvisoryRoute
  '/services/stock-brokerage': typeof ServicesStockBrokerageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/management-team': typeof ManagementTeamRoute
  '/market': typeof MarketRouteWithChildren
  '/news-events': typeof NewsEventsRoute
  '/our-team': typeof OurTeamRoute
  '/support': typeof SupportRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/market/chart': typeof MarketChartRoute
  '/market/floorsheet': typeof MarketFloorsheetRoute
  '/market/live': typeof MarketLiveRoute
  '/market/summary': typeof MarketSummaryRoute
  '/market/top-gainers-losers': typeof MarketTopGainersLosersRoute
  '/services/depository-services': typeof ServicesDepositoryServicesRoute
  '/services/ipo-fpo': typeof ServicesIpoFpoRoute
  '/services/margin-trading': typeof ServicesMarginTradingRoute
  '/services/portfolio-management': typeof ServicesPortfolioManagementRoute
  '/services/research-advisory': typeof ServicesResearchAdvisoryRoute
  '/services/stock-brokerage': typeof ServicesStockBrokerageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/chairman-message': typeof ChairmanMessageRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/management-team': typeof ManagementTeamRoute
  '/market': typeof MarketRouteWithChildren
  '/news-events': typeof NewsEventsRoute
  '/our-team': typeof OurTeamRoute
  '/support': typeof SupportRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/market/chart': typeof MarketChartRoute
  '/market/floorsheet': typeof MarketFloorsheetRoute
  '/market/live': typeof MarketLiveRoute
  '/market/summary': typeof MarketSummaryRoute
  '/market/top-gainers-losers': typeof MarketTopGainersLosersRoute
  '/services/depository-services': typeof ServicesDepositoryServicesRoute
  '/services/ipo-fpo': typeof ServicesIpoFpoRoute
  '/services/margin-trading': typeof ServicesMarginTradingRoute
  '/services/portfolio-management': typeof ServicesPortfolioManagementRoute
  '/services/research-advisory': typeof ServicesResearchAdvisoryRoute
  '/services/stock-brokerage': typeof ServicesStockBrokerageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/chairman-message'
    | '/contact'
    | '/faqs'
    | '/management-team'
    | '/market'
    | '/news-events'
    | '/our-team'
    | '/support'
    | '/branches/$slug'
    | '/market/chart'
    | '/market/floorsheet'
    | '/market/live'
    | '/market/summary'
    | '/market/top-gainers-losers'
    | '/services/depository-services'
    | '/services/ipo-fpo'
    | '/services/margin-trading'
    | '/services/portfolio-management'
    | '/services/research-advisory'
    | '/services/stock-brokerage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/chairman-message'
    | '/contact'
    | '/faqs'
    | '/management-team'
    | '/market'
    | '/news-events'
    | '/our-team'
    | '/support'
    | '/branches/$slug'
    | '/market/chart'
    | '/market/floorsheet'
    | '/market/live'
    | '/market/summary'
    | '/market/top-gainers-losers'
    | '/services/depository-services'
    | '/services/ipo-fpo'
    | '/services/margin-trading'
    | '/services/portfolio-management'
    | '/services/research-advisory'
    | '/services/stock-brokerage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/chairman-message'
    | '/contact'
    | '/faqs'
    | '/management-team'
    | '/market'
    | '/news-events'
    | '/our-team'
    | '/support'
    | '/branches/$slug'
    | '/market/chart'
    | '/market/floorsheet'
    | '/market/live'
    | '/market/summary'
    | '/market/top-gainers-losers'
    | '/services/depository-services'
    | '/services/ipo-fpo'
    | '/services/margin-trading'
    | '/services/portfolio-management'
    | '/services/research-advisory'
    | '/services/stock-brokerage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ChairmanMessageRoute: typeof ChairmanMessageRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ManagementTeamRoute: typeof ManagementTeamRoute
  MarketRoute: typeof MarketRouteWithChildren
  NewsEventsRoute: typeof NewsEventsRoute
  OurTeamRoute: typeof OurTeamRoute
  SupportRoute: typeof SupportRoute
  BranchesSlugRoute: typeof BranchesSlugRoute
  ServicesDepositoryServicesRoute: typeof ServicesDepositoryServicesRoute
  ServicesIpoFpoRoute: typeof ServicesIpoFpoRoute
  ServicesMarginTradingRoute: typeof ServicesMarginTradingRoute
  ServicesPortfolioManagementRoute: typeof ServicesPortfolioManagementRoute
  ServicesResearchAdvisoryRoute: typeof ServicesResearchAdvisoryRoute
  ServicesStockBrokerageRoute: typeof ServicesStockBrokerageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-events': {
      id: '/news-events'
      path: '/news-events'
      fullPath: '/news-events'
      preLoaderRoute: typeof NewsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-team': {
      id: '/management-team'
      path: '/management-team'
      fullPath: '/management-team'
      preLoaderRoute: typeof ManagementTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman-message': {
      id: '/chairman-message'
      path: '/chairman-message'
      fullPath: '/chairman-message'
      preLoaderRoute: typeof ChairmanMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/stock-brokerage': {
      id: '/services/stock-brokerage'
      path: '/services/stock-brokerage'
      fullPath: '/services/stock-brokerage'
      preLoaderRoute: typeof ServicesStockBrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/research-advisory': {
      id: '/services/research-advisory'
      path: '/services/research-advisory'
      fullPath: '/services/research-advisory'
      preLoaderRoute: typeof ServicesResearchAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/portfolio-management': {
      id: '/services/portfolio-management'
      path: '/services/portfolio-management'
      fullPath: '/services/portfolio-management'
      preLoaderRoute: typeof ServicesPortfolioManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/margin-trading': {
      id: '/services/margin-trading'
      path: '/services/margin-trading'
      fullPath: '/services/margin-trading'
      preLoaderRoute: typeof ServicesMarginTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ipo-fpo': {
      id: '/services/ipo-fpo'
      path: '/services/ipo-fpo'
      fullPath: '/services/ipo-fpo'
      preLoaderRoute: typeof ServicesIpoFpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/depository-services': {
      id: '/services/depository-services'
      path: '/services/depository-services'
      fullPath: '/services/depository-services'
      preLoaderRoute: typeof ServicesDepositoryServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/top-gainers-losers': {
      id: '/market/top-gainers-losers'
      path: '/top-gainers-losers'
      fullPath: '/market/top-gainers-losers'
      preLoaderRoute: typeof MarketTopGainersLosersRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/summary': {
      id: '/market/summary'
      path: '/summary'
      fullPath: '/market/summary'
      preLoaderRoute: typeof MarketSummaryRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/live': {
      id: '/market/live'
      path: '/live'
      fullPath: '/market/live'
      preLoaderRoute: typeof MarketLiveRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/floorsheet': {
      id: '/market/floorsheet'
      path: '/floorsheet'
      fullPath: '/market/floorsheet'
      preLoaderRoute: typeof MarketFloorsheetRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/chart': {
      id: '/market/chart'
      path: '/chart'
      fullPath: '/market/chart'
      preLoaderRoute: typeof MarketChartRouteImport
      parentRoute: typeof MarketRoute
    }
    '/branches/$slug': {
      id: '/branches/$slug'
      path: '/branches/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof BranchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketChartRoute: typeof MarketChartRoute
  MarketFloorsheetRoute: typeof MarketFloorsheetRoute
  MarketLiveRoute: typeof MarketLiveRoute
  MarketSummaryRoute: typeof MarketSummaryRoute
  MarketTopGainersLosersRoute: typeof MarketTopGainersLosersRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketChartRoute: MarketChartRoute,
  MarketFloorsheetRoute: MarketFloorsheetRoute,
  MarketLiveRoute: MarketLiveRoute,
  MarketSummaryRoute: MarketSummaryRoute,
  MarketTopGainersLosersRoute: MarketTopGainersLosersRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ChairmanMessageRoute: ChairmanMessageRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ManagementTeamRoute: ManagementTeamRoute,
  MarketRoute: MarketRouteWithChildren,
  NewsEventsRoute: NewsEventsRoute,
  OurTeamRoute: OurTeamRoute,
  SupportRoute: SupportRoute,
  BranchesSlugRoute: BranchesSlugRoute,
  ServicesDepositoryServicesRoute: ServicesDepositoryServicesRoute,
  ServicesIpoFpoRoute: ServicesIpoFpoRoute,
  ServicesMarginTradingRoute: ServicesMarginTradingRoute,
  ServicesPortfolioManagementRoute: ServicesPortfolioManagementRoute,
  ServicesResearchAdvisoryRoute: ServicesResearchAdvisoryRoute,
  ServicesStockBrokerageRoute: ServicesStockBrokerageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
